import type { ToolId } from "../shared/types.ts";
import type { ContextualTerm, DictionaryTerm, TermId } from "./types.ts";

function term(value: DictionaryTerm): DictionaryTerm {
  return value;
}

export const DICTIONARY_TERMS: readonly DictionaryTerm[] = [
  term({ id: "next-decision", label: "Next decision", aliases: ["desired decision", "next move"], plain: "The bounded thing one person or group should decide or do next.", whyItMatters: "A document has no useful shape until its decision job is clear.", changes: "Route, recipient, artefact, ask, order, and what can be parked.", oftenConfusedWith: ["big-goal"], related: ["recipient", "access-route", "artefact"], lenses: { you_are_here: "Selects the live route and primary action.", deck_bones: "Controls the deck's argument and section order.", one_slide_or_three: "Clarifies what the page must help the audience do." } }),
  term({ id: "big-goal", label: "Big goal", aliases: ["dream outcome"], plain: "The larger hope—sell, fund, make, launch, or advance the work.", whyItMatters: "Useful, but too broad to shape the next artefact by itself.", changes: "Context only; it cannot replace a next decision.", oftenConfusedWith: ["next-decision"], related: ["next-decision"], lenses: { you_are_here: "Kept as context while the next actionable decision is named." } }),
  term({ id: "recipient", label: "Recipient", aliases: ["reader", "decision-maker", "next person"], plain: "The person, team, or process that will use this material next.", whyItMatters: "A producer, director, fund, representative, actor, commissioner, and internal team make different decisions.", changes: "Relevance, emphasis, vocabulary, disclosure, ask, and page jobs.", oftenConfusedWith: ["audience"], related: ["next-decision", "access-route", "delivery-mode"], lenses: { you_are_here: "Helps choose who owns the next decision.", deck_bones: "Controls which section jobs belong.", one_slide_or_three: "Changes recipient-sensitive page advice." } }),
  term({ id: "audience", label: "Audience", aliases: ["viewers", "people in the room"], plain: "The people who must glance, read, compare, inspect, remember, or decide while meeting the page.", whyItMatters: "Recipient names the decision owner; audience describes the actual viewing task and conditions.", changes: "Reading support, density tolerance, preview context, and timing relevance.", oftenConfusedWith: ["recipient"], related: ["delivery-mode", "page-job"], lenses: { one_slide_or_three: "Controls physical, temporal, and access context." } }),
  term({ id: "access-route", label: "Access route", aliases: ["submission route", "way in"], plain: "The legitimate way material can reach the recipient: request, relationship, introduction, representative, open process, or accepted cold route.", whyItMatters: "A closed inbox is a route fact, not a quality verdict.", changes: "Whether sending is possible and what first contact may contain.", oftenConfusedWith: ["attachment"], related: ["recipient", "current-requirement"], lenses: { you_are_here: "Can block sending and replace deck work with route-building.", deck_bones: "Stops a send-facing deck when no accepted path exists." } }),
  term({ id: "current-requirement", label: "Current requirement", aliases: ["exact request", "submission requirement"], plain: "A stage-specific item, limit, format, language, disclosure, or prohibition from a current written instruction or direct clarification.", whyItMatters: "It outranks generic advice and famous examples.", changes: "Required, optional, prohibited, order, limits, delivery, and compliance work.", oftenConfusedWith: ["convention"], related: ["source-freshness", "requirement-state"], lenses: { you_are_here: "Can become the primary next action.", deck_bones: "Overrides route defaults and section structure.", one_slide_or_three: "Protects exact text and required sources from provisional bands." } }),
  term({ id: "source-freshness", label: "Source freshness", aliases: ["checked date", "stale source"], plain: "How recently and specifically a requirement or external claim was verified for this route and stage.", whyItMatters: "Old instructions cannot remain binding by nostalgia.", changes: "Confirmed advice may become check-before-sending or conditional.", oftenConfusedWith: ["confidence"], related: ["current-requirement"], lenses: { you_are_here: "Separates current, stale, conflicted, and remembered facts.", deck_bones: "Controls whether exact requirements may override defaults." } }),
  term({ id: "artefact", label: "Artefact", aliases: ["material", "document", "pack"], plain: "The thing being made or sent: script, pilot, overview, deck, bible, treatment, application, rehearsal, or working brief.", whyItMatters: "Different artefacts solve different decisions.", changes: "Questions, content jobs, delivery, limits, and what should not be built.", oftenConfusedWith: ["deck"], related: ["next-decision", "deck", "one-pager", "treatment"], lenses: { you_are_here: "Appears after the route is clear.", deck_bones: "Is selected backstage from decision and recipient facts.", one_slide_or_three: "Provides the page's larger document context." } }),
  term({ id: "deck", label: "Deck", aliases: ["presentation", "slide deck"], plain: "A sequence of pages or slides organised to help a reader or room make a decision.", whyItMatters: "‘Deck’ is not one universal document. Its job, reader, and delivery must be named.", changes: "Whether Deck Bones is useful and which version exists.", oftenConfusedWith: ["pitch-deck", "lookbook", "pitch-bible"], related: ["section-job", "page-job", "delivery-mode"], lenses: { you_are_here: "Runs a deck-existence gate.", deck_bones: "Turns reader questions into an ordered argument.", one_slide_or_three: "Supplies the sequence around an individual page." } }),
  term({ id: "one-pager", label: "One-pager", aliases: ["one page overview", "short project overview"], plain: "A concise, self-contained page that helps a reader understand the project and choose whether to continue.", whyItMatters: "Often more useful than a full deck for a first read or introduction.", changes: "Keeps the first artefact small and the ask bounded.", oftenConfusedWith: ["pitch-deck", "synopsis"], related: ["logline", "synopsis", "next-decision"], lenses: { deck_bones: "Common smallest-useful feature or series route." } }),
  term({ id: "pitch-deck", label: "Pitch deck", aliases: ["project deck", "creative deck"], plain: "A recipient-specific visual and editorial argument about a project, built to support a named decision.", whyItMatters: "It should not become a universal suitcase for story, finance, casting, access, and every future reader.", changes: "Section jobs, delivery version, image use, and ask.", oftenConfusedWith: ["lookbook", "pitch-bible", "finance-deck"], related: ["deck", "section-job", "recipient"], lenses: { you_are_here: "Must earn its existence after higher gates.", deck_bones: "One possible route, never the default answer.", one_slide_or_three: "Gives each page a job and delivery context." } }),
  term({ id: "finance-deck", label: "Finance / project deck", aliases: ["investment deck", "feature finance deck"], plain: "A producer-led project document used inside a qualified financing conversation, combining creative truth with current production, rights, budget, status, risk, pathway, and a precise ask.", whyItMatters: "A creative deck cannot manufacture a budget basis, legal route, returns, recoupment, tax position, or investment claim.", changes: "Activates producing, finance, rights, legal, provenance, and specialist gates.", oftenConfusedWith: ["pitch-deck"], related: ["specialist-first", "attachment"], lenses: { you_are_here: "Requires a real finance decision and qualified producing basis.", deck_bones: "May organise verified section jobs but never draft or validate investment terms.", one_slide_or_three: "Finance pages use inspectable data/reference logic and recipient cautions." } }),
  term({ id: "lookbook", label: "Lookbook", aliases: ["visual lookbook", "vision document"], plain: "A visual document that makes an intended screen world, tone, or directorial interpretation legible.", whyItMatters: "References must serve story and authorship; image volume does not prove a project.", changes: "Visual-language sections, provenance checks, and the director/writer role boundary.", oftenConfusedWith: ["pitch-deck", "directors-treatment"], related: ["comps", "image-provenance"], lenses: { deck_bones: "Useful only when visual interpretation materially helps the decision.", one_slide_or_three: "May contain gallery/reference pages with different density needs." } }),
  term({ id: "treatment", label: "Treatment", aliases: ["story treatment", "film treatment"], plain: "A prose development document describing story, experience, or approach. Its length and job vary by route.", whyItMatters: "A treatment is not automatically a deck or a visual document, and substantial requested treatments may be speculative labour.", changes: "Core-writing route, exact requirement, labour check, and delivery.", oftenConfusedWith: ["directors-treatment", "pitch-deck"], related: ["speculative-work", "current-requirement"], lenses: { you_are_here: "May be exact required work or work that needs scoping first.", deck_bones: "Often sits outside deck structure unless the route explicitly asks for it." } }),
  term({ id: "directors-treatment", label: "Director’s treatment", aliases: ["director treatment", "commercial treatment"], plain: "A director-authored argument for how a project becomes a specific screen experience.", whyItMatters: "It carries authorship, process, labour, and recipient expectations that differ from a generic pitch deck.", changes: "Role authority, visual language, production approach, and speculative-work checks.", oftenConfusedWith: ["treatment", "lookbook"], related: ["image-provenance", "speculative-work"], lenses: { deck_bones: "Deep scripted-feature support exists only where the director role is real; commercial treatment logic remains a future route." } }),
  term({ id: "pitch-bible", label: "Pitch / development bible", aliases: ["series bible", "TV bible", "show bible"], plain: "A concise development document showing what the series is, how it works, who drives it, and where story continues.", whyItMatters: "‘Bible’ is used for several documents. Reader, decision, stage, and requested length must be clarified.", changes: "Series sections, episode evidence, future runway, and document scale.", oftenConfusedWith: ["production-bible", "pitch-deck"], related: ["series-engine", "limited-series", "pilot"], lenses: { you_are_here: "Ambiguous use triggers one clarifying question.", deck_bones: "Uses form-fit series evidence, not famous-template imitation.", one_slide_or_three: "Reference-style pages may legitimately carry more detail." } }),
  term({ id: "production-bible", label: "Production bible", aliases: ["show production bible"], plain: "An operational continuity and reference document used by a commissioned production and writing team.", whyItMatters: "It is not the same as a concise document used to pitch or develop the series.", changes: "Moves the request outside the first Deck Bones release scope.", oftenConfusedWith: ["pitch-bible"], related: ["reference-slide"], lenses: { deck_bones: "Out of scope for the first release; exact current production requirements win." } }),
  term({ id: "pilot", label: "Pilot", aliases: ["pilot script", "first episode"], plain: "The script that launches or demonstrates an episodic work; not every first episode has the same commissioning or series job.", whyItMatters: "A bible cannot quietly replace proof that the pilot carries the promised work.", changes: "Core dependency, sample route, project route, and series evidence.", oftenConfusedWith: ["pitch-bible"], related: ["series-engine", "limited-series"], lenses: { you_are_here: "Pilot state may gate packaging.", deck_bones: "Separates writer/sample decisions from project-sales decisions." } }),
  term({ id: "logline", label: "Logline", aliases: ["series sentence", "premise line"], plain: "A concise statement of protagonist or subject, destabilising force, pursuit, and stakes—or the equivalent project proposition.", whyItMatters: "It orients quickly, but it cannot carry the whole story or prove quality.", changes: "Opening orientation and page-job calibration.", oftenConfusedWith: ["tagline", "synopsis"], related: ["one-pager", "page-job"], lenses: { deck_bones: "A common section job, written by the creator.", one_slide_or_three: "Uses the narrower Film and TV logline page profile." } }),
  term({ id: "tagline", label: "Tagline", aliases: ["marketing line"], plain: "A short evocative line designed to create curiosity or memory.", whyItMatters: "It may sit beside a title, but it does not explain the project like a logline.", changes: "Prevents a mood line from being asked to do orientation work.", oftenConfusedWith: ["logline"], related: ["logline"], lenses: { deck_bones: "May be optional identity copy; never a substitute for premise." } }),
  term({ id: "synopsis", label: "Synopsis", aliases: ["story summary", "series synopsis"], plain: "A prose account of decisive story movement. Feature assessment routes often need the ending; series routes need movement beyond the pilot.", whyItMatters: "A teaser and a synopsis make different promises.", changes: "Story section, length, ending disclosure, and reading burden.", oftenConfusedWith: ["one-pager", "treatment"], related: ["logline", "section-job"], lenses: { deck_bones: "Proves story or series movement when the route needs it.", one_slide_or_three: "Uses story/synopsis copy bands and split boundaries." } }),
  term({ id: "series-engine", label: "Series engine", aliases: ["engine", "repeatable engine"], plain: "The durable pressure, problem, relationship, or structure that keeps producing different episodes.", whyItMatters: "A strong pilot does not automatically prove a returning series.", changes: "Core dependency, series overview, section plan, and page job.", oftenConfusedWith: ["season-arc", "episode-list"], related: ["limited-series", "pilot", "episode-examples"], lenses: { you_are_here: "May become the next piece of work before a deck.", deck_bones: "Controls the format/engine section and route.", one_slide_or_three: "Uses the Film and TV series-engine page profile." } }),
  term({ id: "limited-series", label: "Limited series", aliases: ["finite series", "limited form"], plain: "An episodic story designed to progress toward a real ending rather than reset indefinitely.", whyItMatters: "It should prove necessary progression and duration, not fake a returning engine or invented future seasons.", changes: "Series-form action, arc sections, episode examples, and future-runway omission.", oftenConfusedWith: ["series-engine", "season-arc"], related: ["pilot", "episode-examples"], lenses: { you_are_here: "Selects finite-arc work instead of returning-engine work.", deck_bones: "Replaces repeatability claims with complete progression.", one_slide_or_three: "Changes the job of arc and episode-example pages." } }),
  term({ id: "season-arc", label: "Season arc", aliases: ["first-season arc", "series arc"], plain: "The meaningful progression of pressure, choices, and consequences across a season or finite run.", whyItMatters: "A list of events does not yet show movement.", changes: "Story-order sections and how much future detail belongs.", oftenConfusedWith: ["series-engine", "episode-list"], related: ["limited-series", "episode-examples"], lenses: { deck_bones: "Shows progression appropriate to form.", one_slide_or_three: "Often needs split review when several movements are forced onto one page." } }),
  term({ id: "episode-examples", label: "Episode examples", aliases: ["episode ideas", "episode breakdowns"], plain: "A few distinct examples that test range, repeatability, or finite progression.", whyItMatters: "They are evidence of form, not wallpaper or a volume contest.", changes: "Whether the project can support a series pitch and how pages are divided.", oftenConfusedWith: ["episode-list", "series-engine"], related: ["series-engine", "limited-series"], lenses: { deck_bones: "Optional or main evidence depending on route.", one_slide_or_three: "Uses a case-study profile; full synopses may need separate pages." } }),
  term({ id: "episode-list", label: "Episode list", aliases: ["episode catalogue"], plain: "A list of instalments or titles, which may or may not prove movement or repeatability.", whyItMatters: "Volume can conceal that every example tests the same beat.", changes: "May be parked until examples have distinct decision work.", oftenConfusedWith: ["episode-examples", "series-engine"], related: ["episode-examples"], lenses: { deck_bones: "Never treated as proof by existence alone." } }),
  term({ id: "section-job", label: "Section job", aliases: ["argument unit", "content job"], plain: "One reader question a part of the deck must answer. It is not automatically one slide.", whyItMatters: "Structure should follow decision work, not template categories or page-count folklore.", changes: "Section inclusion, order, reuse, completion, and omission.", oftenConfusedWith: ["page-job"], related: ["reader-question", "appendix"], lenses: { deck_bones: "The core unit of deck structure.", one_slide_or_three: "Becomes page context when copy is tested." } }),
  term({ id: "reader-question", label: "Reader question", aliases: ["decision question"], plain: "The concrete thing a reader must understand before they can make the next decision.", whyItMatters: "Every section and page should earn its place by answering one.", changes: "Argument order, evidence selection, and finish checks.", oftenConfusedWith: ["recipient-doubt"], related: ["section-job", "page-job"], lenses: { deck_bones: "Maps the deck from orientation to ask.", one_slide_or_three: "Clarifies which page job the visible copy serves." } }),
  term({ id: "recipient-doubt", label: "Recipient doubt", aliases: ["likely question", "reasonable concern"], plain: "A route-relevant uncertainty the next person may need resolved, stated cautiously and never mind-read as fact.", whyItMatters: "The smallest useful artefact often exists to answer this one uncertainty.", changes: "Action, section priority, and explanation.", oftenConfusedWith: ["reader-question"], related: ["recipient", "next-decision"], lenses: { you_are_here: "May select between otherwise viable next actions.", deck_bones: "May promote one section job over another." } }),
  term({ id: "page-job", label: "Page job", aliases: ["slide job", "slide role"], plain: "The single primary thing a page helps its audience do: orient, grasp a premise, follow story, compare, inspect evidence, understand process, or act.", whyItMatters: "Word load means different things on a cover, logline, synopsis, data page, gallery, ask, or appendix.", changes: "Copy band, structure check, route profile, and advice.", oftenConfusedWith: ["section-job"], related: ["delivery-mode", "copy-band"], lenses: { deck_bones: "Each section hands a suggested page job forward.", one_slide_or_three: "The primary context after delivery." } }),
  term({ id: "delivery-mode", label: "Delivery mode", aliases: ["how it is used", "reading mode"], plain: "How people meet the material: spoken live, guided, read alone, dual-use, or as reference.", whyItMatters: "A live cue and a leave-behind have different responsibilities.", changes: "Structure, copy band, timing, navigation, source detail, and versioning.", oftenConfusedWith: ["audience"], related: ["live-deck", "leave-behind", "dual-use"], lenses: { you_are_here: "Changes the useful artefact and immediate action.", deck_bones: "Changes the document version and section treatment.", one_slide_or_three: "Controls timing, copy bands, and channel checks." } }),
  term({ id: "live-deck", label: "Live deck", aliases: ["speaker-led deck", "pitch support"], plain: "A deck that supports a presenter and room rather than surviving as a complete document by itself.", whyItMatters: "Dense paragraphs may compete with speech; rehearsal may matter more than another slide.", changes: "Cueing, copy, timing, backup, and ask.", oftenConfusedWith: ["leave-behind", "pre-read"], related: ["delivery-mode", "dual-use"], lenses: { deck_bones: "May become a rehearsal route or separate version.", one_slide_or_three: "Uses speaker-led physical and channel checks." } }),
  term({ id: "leave-behind", label: "Leave-behind", aliases: ["circulating deck", "read-alone version"], plain: "The version someone keeps and understands without the presenter.", whyItMatters: "It needs context, navigation, truthful status, and a complete ask, but not a transcript of the meeting.", changes: "Document structure, disclosure, density, sources, and contact information.", oftenConfusedWith: ["live-deck", "pre-read"], related: ["delivery-mode", "dual-use"], lenses: { deck_bones: "May require a separate version from live support.", one_slide_or_three: "Uses self-read page jobs and physical preview." } }),
  term({ id: "pre-read", label: "Pre-read", aliases: ["read before meeting"], plain: "Material sent before a conversation so the room arrives with shared context.", whyItMatters: "It must survive alone while leaving the meeting something useful to do.", changes: "Navigation, context, density, and conversation design.", oftenConfusedWith: ["leave-behind", "live-deck"], related: ["delivery-mode"], lenses: { deck_bones: "Shapes the reading path before the live decision.", one_slide_or_three: "Often maps to guided or self-read checks depending on use." } }),
  term({ id: "reference-slide", label: "Reference page", aliases: ["appendix page", "reference slide"], plain: "A page the audience controls and inspects for detail rather than meeting briefly in a live sequence.", whyItMatters: "Higher density may be honest when navigation, type, and reading control work.", changes: "Copy budget, timing relevance, and appendix placement.", oftenConfusedWith: ["leave-behind"], related: ["appendix", "copy-band"], lenses: { deck_bones: "Often belongs after the main argument.", one_slide_or_three: "Can receive a reference-density exception." } }),
  term({ id: "dual-use", label: "Dual-use deck", aliases: ["one deck for live and read", "hybrid deck"], plain: "One file expected to support a live presentation and also make full sense when read alone.", whyItMatters: "The two jobs often create conflicting density and context needs.", changes: "May trigger separate live and read versions rather than a compromised average.", oftenConfusedWith: ["leave-behind", "live-deck"], related: ["delivery-mode", "channel-competition"], lenses: { deck_bones: "Splits document versions when decisions or delivery jobs differ.", one_slide_or_three: "Compares live and self-read bands and may recommend separate versions." } }),
  term({ id: "appendix", label: "Appendix", aliases: ["backup slides", "supporting material"], plain: "Useful detail kept outside the main reading path for questions, diligence, or reference.", whyItMatters: "It protects the argument without deleting material that has a later job.", changes: "Section status, order, and density expectations.", oftenConfusedWith: ["reference-slide"], related: ["section-job", "leave-behind"], lenses: { deck_bones: "A section state, never a dumping ground.", one_slide_or_three: "Reference pages use different copy and timing logic." } }),
  term({ id: "comps", label: "Comps", aliases: ["comparable works", "comparisons"], plain: "Works used to clarify one declared relationship: tone, audience, format, scale, structure, visual language, or positioning.", whyItMatters: "Fame does not prove demand. Each comp needs a job, a difference, and a misleading inference to avoid.", changes: "Whether a comparison belongs and what its page must say.", oftenConfusedWith: ["market-proof"], related: ["image-provenance"], lenses: { deck_bones: "Lives inside the Film and TV section library, not as a standalone oracle.", one_slide_or_three: "Comparison pages are inspectable, not automatically sparse." } }),
  term({ id: "market-proof", label: "Market proof", aliases: ["proof of demand"], plain: "Current, relevant evidence that people or buyers behave in a claimed way—not a famous title or hopeful logo.", whyItMatters: "The tools cannot infer buyer appetite or audience size from comps.", changes: "Unsupported claims become source, verification, or specialist tasks.", oftenConfusedWith: ["comps"], related: ["source-freshness"], lenses: { deck_bones: "Never manufactured from design or comparison alone." } }),
  term({ id: "attachment", label: "Attachment", aliases: ["attached talent", "attached producer", "attached director"], plain: "A person or company with a real current level of commitment to the project, described no more strongly than the evidence supports.", whyItMatters: "Interest, a read request, an informal exploration, and a formal attachment are not the same fact.", changes: "Status copy, programme eligibility, team sections, and disclosure.", oftenConfusedWith: ["access-route"], related: ["requirement-state", "recipient"], lenses: { you_are_here: "May change route and eligibility but never quality.", deck_bones: "Controls truthful team/status language and specialist checks." } }),
  term({ id: "image-provenance", label: "Image provenance", aliases: ["image rights", "asset source"], plain: "Where an image came from, who controls it, and whether its intended use is permitted and ethically sound.", whyItMatters: "Finding an image online does not establish permission; adjacency can also imply false attachment.", changes: "Whether an asset may travel, must be replaced, or needs a narrow specialist check.", oftenConfusedWith: ["visual-reference"], related: ["lookbook", "comps"], lenses: { deck_bones: "Unsafe assets are removed without freezing unrelated creative work." } }),
  term({ id: "protect-this", label: "Protect This", aliases: ["creative boundary", "north star line"], plain: "An optional creator-written truth, boundary, responsibility, or priority worth carrying into pitching and collaboration.", whyItMatters: "Movement should not require the work to surrender the thing that makes it itself.", changes: "Reflection and handoff only. It never changes eligibility, ranking, or route priority.", oftenConfusedWith: ["theme"], related: ["next-decision"], lenses: { you_are_here: "Appears in the six-part result as an optional local line.", deck_bones: "May inform what sections must not flatten or overclaim.", one_slide_or_three: "May help the user reject a mechanically neat split that damages meaning." } }),
  term({ id: "copy-band", label: "Copy band", aliases: ["word band", "copy budget"], plain: "A provisional editorial range for visible words and blocks, adjusted by page job and delivery mode.", whyItMatters: "It is a review trigger, not science and not proof that a page fits.", changes: "Directional keep, tight, or split pressure.", oftenConfusedWith: ["preview-fit"], related: ["page-job", "delivery-mode", "type-pressure"], lenses: { one_slide_or_three: "One independent check among physical fit, time, structure, type, and channel competition." } }),
  term({ id: "preview-fit", label: "Preview fit", aliases: ["rendered fit", "physical fit"], plain: "Whether the real rendered page fits after content, fonts, layout, and viewport are applied.", whyItMatters: "Word count cannot prove physical fit.", changes: "Measured keep, tight, overflow, or abstention states.", oftenConfusedWith: ["copy-band"], related: ["type-pressure", "smallest-view"], lenses: { one_slide_or_three: "Rendered DOM owns the physical verdict and invalidates when inputs change." } }),
  term({ id: "smallest-view", label: "Smallest real view", aliases: ["preview context", "viewing context"], plain: "The smallest or hardest real condition in which the page must remain usable: phone, laptop, video call, room, print, or mixed setting.", whyItMatters: "A page that fits the editor canvas may fail where people actually meet it.", changes: "Preview preset, type expectation, and result footing.", oftenConfusedWith: ["audience"], related: ["preview-fit"], lenses: { one_slide_or_three: "Asked before claiming physical confidence." } }),
  term({ id: "type-pressure", label: "Type pressure", aliases: ["small type", "shrink-to-fit"], plain: "Whether copy fits only because type was pushed below the selected minimum or reading expectation.", whyItMatters: "Smaller type must never manufacture a pass.", changes: "Physical failure or tightness and the recommended change.", oftenConfusedWith: ["preview-fit"], related: ["copy-band"], lenses: { one_slide_or_three: "A separate check; fitting below the selected minimum still fails." } }),
  term({ id: "channel-competition", label: "Channel competition", aliases: ["reading while listening", "duplicate speech"], plain: "The load created when people must read visible copy while also listening to the same or different spoken words.", whyItMatters: "Duplicate live copy can compete with the presenter, while intentional reading support may be necessary.", changes: "Rework delivery/copy, separate versions, or apply a text-support exception.", oftenConfusedWith: ["copy-band"], related: ["dual-use", "live-deck"], lenses: { one_slide_or_three: "Tests speech-text relationship without assuming all visible copy is a talk track." } }),
  term({ id: "split-source", label: "Split source", aliases: ["boundary coordinate text"], plain: "The exact normalised body string against which every suggested split index is measured.", whyItMatters: "It prevents the interface from cutting untouched text at the wrong position.", changes: "How split previews and edits map safely back to copy.", oftenConfusedWith: ["rewritten-copy"], related: ["mechanical-split"], lenses: { one_slide_or_three: "A technical contract: split indices always belong to `splitSource`." } }),
  term({ id: "mechanical-split", label: "Mechanical split", aliases: ["split candidate", "boundary suggestion"], plain: "A possible break at an existing paragraph, bullet group, or sentence boundary.", whyItMatters: "It suggests where review may begin; it does not claim the resulting pages make semantic sense.", changes: "Two- or three-page review plan, never automatic rewrite or commit.", oftenConfusedWith: ["rewritten-copy"], related: ["split-source"], lenses: { one_slide_or_three: "User reviews, moves, rejects, or edits every split, then remeasures." } }),
  term({ id: "result-footing", label: "Result footing", aliases: ["result strength", "basis"], plain: "A plain statement of whether advice comes from measurement, direction, user observation, current source, or limited context.", whyItMatters: "Confidence should describe evidence, never project quality.", changes: "How strongly the product speaks and which fact it asks for next.", oftenConfusedWith: ["score", "confidence"], related: ["source-freshness"], lenses: { you_are_here: "Uses specific, best-route, private-plan, and check-before-sending states.", deck_bones: "Uses confirmed, conditional, and exploratory routes.", one_slide_or_three: "Uses measured, directional, and context-limited results." } }),
  term({ id: "reuse-state", label: "Reuse state", aliases: ["material state"], plain: "Whether existing material can be reused, revised, checked first, is missing, or belongs outside this version.", whyItMatters: "A new route should not make previous work feel discarded by default.", changes: "Task order and how much new work is assigned.", oftenConfusedWith: ["requirement-state"], related: ["section-job"], lenses: { deck_bones: "Mapped before missing-work tasks are created." } }),
  term({ id: "requirement-state", label: "Requirement state", aliases: ["section status"], plain: "Whether material is required, recommended, optional, appendix, missing, blocked, or excluded for this exact route.", whyItMatters: "Importance and existence are different facts.", changes: "What enters the main path and what task or caution appears.", oftenConfusedWith: ["reuse-state"], related: ["current-requirement"], lenses: { deck_bones: "Applied per section after gates and exact requirements." } }),
  term({ id: "specialist-first", label: "Needs specialist input first", aliases: ["specialist boundary", "human boundary"], plain: "A narrow legal, rights, labour, finance, safety, privacy, or comparable claim must be checked by current qualified guidance before that claim or use proceeds.", whyItMatters: "The risky issue should not freeze unrelated creative work or become a vague paid referral.", changes: "Blocks one claim or action, creates a precise brief, and preserves a safe fallback.", oftenConfusedWith: ["paid-help"], related: ["current-requirement"], lenses: { you_are_here: "May become the primary action when the issue is binding.", deck_bones: "Removes or labels the unsupported claim while the rest of the structure continues." } }),
  term({ id: "speculative-work", label: "Speculative work", aliases: ["free work", "unpaid treatment", "unpaid pitch"], plain: "Custom work requested before the process, ownership, use, compensation, competition, recording, leave-behind, or applicable agreement is clear.", whyItMatters: "Prestige and urgency do not answer material labour questions.", changes: "Pauses substantial work and creates a scoped clarification or current guild/union question.", oftenConfusedWith: ["portfolio-work"], related: ["specialist-first", "treatment"], lenses: { you_are_here: "Can outrank deck work.", deck_bones: "Stops extensive custom packaging until the process is understood." } }),
  term({ id: "theme", label: "Theme", aliases: ["thematic question", "meaning"], plain: "A recurring question, tension, or idea explored through the work rather than a lesson pasted above it.", whyItMatters: "Theme may guide what the work protects, but the tool cannot write or grade it.", changes: "May influence a section's job or a creator's private boundary, never route eligibility.", oftenConfusedWith: ["protect-this"], related: ["protect-this"], lenses: { deck_bones: "A section job only when it helps this reader understand the project.", one_slide_or_three: "A thematic page still needs a concrete page job." } }),
  term({ id: "confidence", label: "Confidence", aliases: ["certainty", "self-confidence"], plain: "How sure a person feels. It is not evidence that a project, route, or claim is ready.", whyItMatters: "Anxiety cannot lower factual readiness; confidence cannot raise it.", changes: "Nothing in route priority by itself.", oftenConfusedWith: ["result-footing"], related: ["result-footing"], lenses: { you_are_here: "Never scored or used as a readiness proxy.", deck_bones: "Never used to bypass a prerequisite.", one_slide_or_three: "Result strength describes evidence, not confidence." } }),
  term({ id: "score", label: "Score", aliases: ["readiness score", "confidence score"], plain: "A number that collapses different facts into one rank.", whyItMatters: "This family rejects scores because hard gates, current requirements, and missing prerequisites cannot responsibly cancel each other out.", changes: "Nothing; no score exists in the product.", oftenConfusedWith: ["result-footing"], related: ["confidence"], lenses: { you_are_here: "Uses ordered rules and reasons.", deck_bones: "Uses one route, gates, and section states.", one_slide_or_three: "Uses independent checks and evidence footing." } }),
  term({ id: "rewritten-copy", label: "Rewritten copy", aliases: ["automatic rewrite", "generated copy"], plain: "New wording created in place of the creator's original text.", whyItMatters: "One Slide or Three? does not need a generative rewrite to identify mechanical pressure or boundaries.", changes: "Outside the core path; original copy remains preserved.", oftenConfusedWith: ["mechanical-split"], related: ["split-source"], lenses: { one_slide_or_three: "Never auto-generated or auto-committed by the core engine." } }),
  term({ id: "paid-help", label: "Paid help", aliases: ["professional help", "pitch consultant"], plain: "A scoped human service that may help when a real craft or specialist job is clear.", whyItMatters: "It must not become the price of receiving the free result or a vague cure for uncertainty.", changes: "May appear after the complete result when timing, job, scope, and self-directed fallback are explicit.", oftenConfusedWith: ["specialist-first"], related: ["specialist-first"], lenses: { you_are_here: "Never part of action eligibility.", deck_bones: "Appears only after the plan is complete and owned by the user." } }),
  term({ id: "portfolio-work", label: "Portfolio work", aliases: ["self-initiated work", "practice piece"], plain: "Work a creator chooses to make for learning, expression, or demonstration without a recipient commissioning custom solutions.", whyItMatters: "Chosen practice and requested speculative labour have different power and use conditions.", changes: "May remain private or self-directed rather than triggering a labour gate.", oftenConfusedWith: ["speculative-work"], related: ["speculative-work"], lenses: { you_are_here: "Kept separate from coercive or undefined requested work." } }),
  term({ id: "visual-reference", label: "Visual reference", aliases: ["reference image", "mood image"], plain: "An image used to discuss tone, world, craft, scale, or another declared relationship without claiming ownership or attachment.", whyItMatters: "Reference intent does not erase provenance, permission, privacy, or false-inference risk.", changes: "Image status, captioning, placement, and whether the asset can travel.", oftenConfusedWith: ["image-provenance"], related: ["comps", "lookbook"], lenses: { deck_bones: "May support a section only when its job and use boundary are clear.", one_slide_or_three: "Visual-only or gallery pages require intentional context, not invented copy." } }),
  term({ id: "convention", label: "Convention", aliases: ["common practice", "typical approach"], plain: "A pattern practitioners often use, not a binding requirement or universal law.", whyItMatters: "Convention may guide a conditional suggestion but cannot outvote a current request or hard gate.", changes: "Result footing and how strongly copy speaks.", oftenConfusedWith: ["current-requirement"], related: ["result-footing"], lenses: { you_are_here: "Stays below current requirements and dependencies.", deck_bones: "Informs defaults that remain inspectable and replaceable.", one_slide_or_three: "Copy bands remain provisional editorial judgement until calibrated." } }),
] as const;

const BY_ID = new Map(DICTIONARY_TERMS.map((item) => [item.id, item]));

export function getTerm(id: TermId): DictionaryTerm | undefined {
  return BY_ID.get(id);
}

export function contextualiseTerm(id: TermId, tool: ToolId): ContextualTerm | undefined {
  const value = getTerm(id);
  if (!value) return undefined;
  return { ...value, activeTool: tool, here: value.lenses[tool] ?? value.whyItMatters };
}

export function termsForTool(tool: ToolId): DictionaryTerm[] {
  return DICTIONARY_TERMS.filter((item) => item.lenses[tool]);
}

function normalise(value: string): string {
  return value.trim().toLocaleLowerCase("en").replace(/[’']/g, "'");
}

export function searchTerms(query: string, tool?: ToolId, limit = 12): DictionaryTerm[] {
  const needle = normalise(query);
  const pool = tool ? termsForTool(tool) : [...DICTIONARY_TERMS];
  if (!needle) return pool.slice(0, limit);
  return pool
    .map((item) => {
      const label = normalise(item.label);
      const aliases = item.aliases.map(normalise);
      const exact = label === needle || aliases.includes(needle);
      const starts = label.startsWith(needle) || aliases.some((alias) => alias.startsWith(needle));
      const contains = label.includes(needle) || aliases.some((alias) => alias.includes(needle)) || normalise(item.plain).includes(needle);
      return { item, score: exact ? 3 : starts ? 2 : contains ? 1 : 0 };
    })
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score || a.item.label.localeCompare(b.item.label))
    .slice(0, limit)
    .map(({ item }) => item);
}

export function validateDictionary(): string[] {
  const problems: string[] = [];
  const ids = new Set<string>();
  for (const item of DICTIONARY_TERMS) {
    if (ids.has(item.id)) problems.push(`Duplicate term ID: ${item.id}`);
    ids.add(item.id);
  }
  for (const item of DICTIONARY_TERMS) {
    for (const ref of [...item.oftenConfusedWith, ...item.related]) {
      if (!BY_ID.has(ref)) problems.push(`${item.id} references missing term ${ref}`);
    }
  }
  return problems;
}
