import { DICTIONARY_TERMS } from "../engine/dictionary/index.ts";
import type { DictionaryTerm } from "../engine/dictionary/types.ts";

export type Category = "Foundations" | "Story & screen" | "Advertising" | "Business & startups" | "Rooms & slides" | "Evidence & claims" | "Rights, labour & process" | "Access & inclusion";
export interface PitchTerm extends DictionaryTerm { category: Category; }
interface Seed { id: string; label: string; aliases?: string[]; plain: string; why: string; changes: string; category: Category; }
const s = (value: Seed): PitchTerm => ({ id: value.id, label: value.label, aliases: value.aliases ?? [], plain: value.plain, whyItMatters: value.why, changes: value.changes, oftenConfusedWith: [], related: [], lenses: {}, category: value.category });

const US_SPELLING: Readonly<Record<string, string>> = {
  artefact: "artifact", artefacts: "artifacts", behaviour: "behavior", behaviours: "behaviors",
  capitalisation: "capitalization", catalogue: "catalog", catalogues: "catalogs", centre: "center", centred: "centered",
  colour: "color", colours: "colors", fulfil: "fulfill", fulfils: "fulfills", instalment: "installment", instalments: "installments",
  judgement: "judgment", labour: "labor", licence: "license", licences: "licenses", localisation: "localization",
  modelling: "modeling", neighbour: "neighbor", neighbouring: "neighboring", neighbours: "neighbors",
  organisation: "organization", organisations: "organizations", organise: "organize", organised: "organized",
  organises: "organizes", organising: "organizing", prioritise: "prioritize", prioritised: "prioritized",
  prioritises: "prioritizes", prioritising: "prioritizing", programme: "program", programmes: "programs",
  recognise: "recognize", recognised: "recognized", recognises: "recognizes", recognising: "recognizing", travelling: "traveling",
};

export function usEnglish(value: string): string {
  return value.replace(/\b(artefacts?|behaviou?rs?|capitalisation|catalogues?|centred?|colours?|fulfils?|instalments?|judgement|labour|licences?|localisation|modelling|neighbours?|neighbouring|organisations?|organis(?:e|ed|es|ing)|prioritis(?:e|ed|es|ing)|programmes?|recognis(?:e|ed|es|ing)|travelling)\b/gi, (word) => {
    const replacement = US_SPELLING[word.toLowerCase()] ?? word;
    return /^[A-Z]/.test(word) ? replacement[0]!.toUpperCase() + replacement.slice(1) : replacement;
  });
}

function forDisplay(term: PitchTerm): PitchTerm {
  return {
    ...term,
    label: usEnglish(term.label),
    aliases: [...new Set([...term.aliases, ...term.aliases.map(usEnglish)])],
    plain: usEnglish(term.plain),
    whyItMatters: usEnglish(term.whyItMatters),
    changes: usEnglish(term.changes),
  };
}

const EXTRA: readonly PitchTerm[] = [
  s({ id:"pitch", label:"Pitch", aliases:["project pitch","sales pitch"], plain:"A bounded attempt to help a particular person understand something and choose what to do next.", why:"A pitch is a decision experience—not a performance of certainty.", changes:"Reader, argument, proof, delivery, and ask.", category:"Foundations" }),
  s({ id:"brief", label:"Brief", aliases:["project brief","assignment"], plain:"The current statement of the problem, objective, audience, constraints, deliverables, timing, and decision.", why:"A vague or stale brief creates expensive precision around the wrong job.", changes:"Scope, requirements, route, and what must be clarified first.", category:"Foundations" }),
  s({ id:"creative-brief", label:"Creative brief", aliases:["creative strategy brief"], plain:"A working contract for the communication problem: audience, objective, insight, proposition, evidence, tone, and mandatories.", why:"It should sharpen the creative problem without pre-solving the creative answer.", changes:"Concept evaluation, deliverables, and client alignment.", category:"Advertising" }),
  s({ id:"proposition", label:"Proposition", aliases:["core proposition","value proposition"], plain:"The central thing the pitch asks someone to believe, value, or act on.", why:"A list of features or themes is not yet one graspable promise.", changes:"Headline, evidence, order, and ask.", category:"Foundations" }),
  s({ id:"value-proposition", label:"Value proposition", aliases:["value prop"], plain:"Why a particular group should choose this offer over doing nothing or using an alternative.", why:"It connects a real need to a specific benefit and believable difference.", changes:"Positioning, proof, audience, and product story.", category:"Business & startups" }),
  s({ id:"insight", label:"Insight", aliases:["human insight","customer insight"], plain:"A useful explanation of a tension, behaviour, or condition that changes how the problem should be approached.", why:"An observation says what happened; an insight explains a useful why without pretending universality.", changes:"Strategy, concept, audience framing, and proof needs.", category:"Foundations" }),
  s({ id:"tension", label:"Tension", aliases:["core tension"], plain:"Two forces, needs, truths, or consequences that cannot be comfortably satisfied at once.", why:"Tension creates movement; a topic alone does not.", changes:"Story, insight, positioning, and the order of the argument.", category:"Foundations" }),
  s({ id:"hook", label:"Hook", aliases:["opening hook"], plain:"The specific element that earns attention or curiosity long enough for the proposition to become clear.", why:"A hook opens the door. It does not excuse withholding the point forever.", changes:"Opening, title, sequence, and first proof.", category:"Foundations" }),
  s({ id:"ask", label:"Ask", aliases:["the ask","request"], plain:"The explicit action or decision requested from the recipient now.", why:"‘Support us’ is a mood. A useful ask names who should do what next.", changes:"Close, route, evidence, and follow-up.", category:"Foundations" }),
  s({ id:"call-to-action", label:"Call to action", aliases:["CTA","next action"], plain:"The visible instruction that tells people what action is available next.", why:"It should fit the decision and the user’s actual power—not manufacture urgency.", changes:"Button, close, follow-up, and conversion path.", category:"Rooms & slides" }),
  s({ id:"objection", label:"Objection", aliases:["concern","barrier"], plain:"A stated reason a recipient may hesitate, decline, or need more evidence.", why:"A real objection is evidence; an imagined objection is a hypothesis.", changes:"Proof, order, follow-up, and whether a specialist is needed.", category:"Foundations" }),
  s({ id:"decision-criteria", label:"Decision criteria", aliases:["selection criteria","buying criteria"], plain:"The facts or conditions a decision owner will use to choose, approve, shortlist, or reject.", why:"A pitch cannot be relevant if it ignores how the decision is actually made.", changes:"Evidence, emphasis, compliance, and questions to clarify.", category:"Foundations" }),
  s({ id:"stakeholder", label:"Stakeholder", aliases:["interested party"], plain:"A person or group materially affected by the decision or able to shape it.", why:"Stakeholders are not automatically the decision owner or the end user.", changes:"Consultation, disclosure, sequencing, and versioning.", category:"Foundations" }),
  s({ id:"decision-owner", label:"Decision owner", aliases:["economic buyer","approver","who can decide","who says yes"], plain:"The person or body with the actual authority to make the next decision.", why:"Influence, use, recommendation, and approval are different powers.", changes:"Recipient, ask, proof, and access route.", category:"Foundations" }),
  s({ id:"end-user", label:"End user", aliases:["user","operator"], plain:"The person who will actually use, experience, or live with what is being proposed.", why:"The buyer and user may have different needs and evidence.", changes:"Research, product story, accessibility, and success measures.", category:"Business & startups" }),
  s({ id:"positioning", label:"Positioning", aliases:["market position"], plain:"The useful place an offer or work occupies in a particular audience’s mind relative to alternatives and the status quo.", why:"Positioning is relational; adjectives alone do not create it.", changes:"Audience, comparisons, value proposition, and language.", category:"Foundations" }),
  s({ id:"differentiator", label:"Differentiator", aliases:["point of difference","USP"], plain:"A relevant difference the intended recipient can understand and the evidence can support.", why:"Being unusual is not enough; the difference must matter for this decision.", changes:"Claim, proof, comparisons, and product story.", category:"Foundations" }),
  s({ id:"elevator-pitch", label:"Elevator pitch", aliases:["short pitch","30-second pitch"], plain:"A compact spoken orientation: what this is, for whom, why it matters, and what conversation should happen next.", why:"It opens a longer exchange; it is not a miniature encyclopedia.", changes:"Opening language and what gets parked.", category:"Rooms & slides" }),
  s({ id:"pitch-narrative", label:"Pitch narrative", aliases:["deck story","argument arc"], plain:"The ordered movement from shared reality through proposition and proof to a clear next decision.", why:"A pile of correct pages is not yet an argument.", changes:"Sequence, transitions, proof placement, and close.", category:"Rooms & slides" }),
  s({ id:"premise", label:"Premise", aliases:["story premise","series premise"], plain:"The central dramatic or conceptual situation from which the work’s movement grows.", why:"A premise creates possibility; it does not by itself prove a complete story or series.", changes:"Logline, synopsis, engine, and opening pages.", category:"Story & screen" }),
  s({ id:"protagonist", label:"Protagonist", aliases:["lead character"], plain:"The person or force whose choices, pursuit, and consequences principally organise the audience’s journey.", why:"The protagonist is not always the nicest, loudest, or most visible character.", changes:"Logline, synopsis, character pages, and stakes.", category:"Story & screen" }),
  s({ id:"antagonistic-force", label:"Antagonistic force", aliases:["opposition","antagonist"], plain:"The person, system, condition, relationship, or inner contradiction that materially resists the protagonist’s pursuit.", why:"Opposition creates pressure; a villain label can flatten a more complex force.", changes:"Logline, story movement, and character relationships.", category:"Story & screen" }),
  s({ id:"inciting-incident", label:"Inciting incident", aliases:["inciting event","catalyst"], plain:"The disruption that makes the prior equilibrium untenable and launches the central movement.", why:"It is a functional turn, not simply the first exciting event.", changes:"Synopsis, structure, and story orientation.", category:"Story & screen" }),
  s({ id:"stakes", label:"Stakes", aliases:["what is at stake","consequences"], plain:"The meaningful consequences of action, failure, delay, or change for the people and world involved.", why:"Bigger danger is not automatically deeper stakes; specificity makes consequence felt.", changes:"Logline, story pages, urgency, and the ask.", category:"Story & screen" }),
  s({ id:"character-arc", label:"Character arc", aliases:["character journey"], plain:"A meaningful change—or revealing refusal to change—produced by pressure, choices, and consequences.", why:"A biography or list of traits does not show movement.", changes:"Synopsis, character page, season arc, and ending.", category:"Story & screen" }),
  s({ id:"story-arc", label:"Story arc", aliases:["narrative arc"], plain:"The causal movement of pressure, choices, turns, and consequences across the intended story.", why:"Chronology alone is not an arc.", changes:"Synopsis, section order, and split decisions.", category:"Story & screen" }),
  s({ id:"beat", label:"Beat", aliases:["story beat","dramatic beat"], plain:"A distinct unit of dramatic action, information, or emotional change.", why:"Beats help inspect movement; rigid beat worship can make different stories look identical.", changes:"Outline, synopsis, scene logic, and page sequence.", category:"Story & screen" }),
  s({ id:"beat-sheet", label:"Beat sheet", aliases:["beats"], plain:"A compact list of major dramatic beats used to inspect story movement before or during drafting.", why:"It is a development tool, not proof that the scenes work.", changes:"Core-writing route and synopsis readiness.", category:"Story & screen" }),
  s({ id:"outline", label:"Outline", aliases:["story outline","episode outline"], plain:"A structured account of intended story movement before the full script exists.", why:"It can expose causal gaps while remaining different from a readable screenplay.", changes:"Writing stage, feedback question, and what packaging should wait.", category:"Story & screen" }),
  s({ id:"screenplay", label:"Screenplay", aliases:["script","feature script"], plain:"The written dramatic work specifying scenes, action, dialogue, and the intended screen experience.", why:"A pitch can orient people to a screenplay; it cannot substitute for the pages when the pages are the proof.", changes:"Stage gates, read route, and what the deck may claim.", category:"Story & screen" }),
  s({ id:"writing-sample", label:"Writing sample", aliases:["sample script","staffing sample"], plain:"Writing assessed primarily as evidence of the writer’s craft, voice, or fit rather than as a project acquisition package.", why:"A sample route and a project-sales route ask different questions.", changes:"Recipient, artefact, context, and whether a deck belongs.", category:"Story & screen" }),
  s({ id:"format", label:"Format", aliases:["project format","screen format"], plain:"The work’s intended form: feature, series, short, documentary, commercial, presentation, and so on.", why:"Form creates real structural expectations, but convention does not become law.", changes:"Core evidence, vocabulary, route, and section jobs.", category:"Story & screen" }),
  s({ id:"genre", label:"Genre", aliases:["story genre"], plain:"A set of audience promises and story conventions the work uses, bends, combines, or rejects.", why:"Genre is an experience contract, not a shelf label alone.", changes:"Tone, stakes, comparisons, and reader expectations.", category:"Story & screen" }),
  s({ id:"tone", label:"Tone", aliases:["tonal language","feel"], plain:"The work’s attitude and emotional handling of its material, expressed through choices rather than an adjective cloud.", why:"‘Dark but funny’ is a starting signal, not yet a tangible screen experience.", changes:"Examples, visual language, writing, and comps.", category:"Story & screen" }),
  s({ id:"world", label:"World", aliases:["story world","arena"], plain:"The place, systems, rules, textures, access, and power conditions that generate story.", why:"A location list does not explain why this story can happen only here.", changes:"World page, conflicts, production approach, and visual language.", category:"Story & screen" }),
  s({ id:"creator-statement", label:"Creator statement", aliases:["why me","writer statement"], plain:"A concise account of the creator’s genuine relationship to the work and the perspective shaping it.", why:"Connection matters; trauma should not be demanded as proof of worthiness.", changes:"Authorship page, tone, disclosure, and boundaries.", category:"Story & screen" }),
  s({ id:"directors-statement", label:"Director’s statement", aliases:["director note","directing statement"], plain:"The director’s specific interpretation of the material and how craft choices change the audience’s experience.", why:"A moodboard is not yet an authored directing idea.", changes:"Visual language, method, references, and role authority.", category:"Story & screen" }),
  s({ id:"showrunner", label:"Showrunner", aliases:["writer-showrunner"], plain:"The lead creative producer responsible for the ongoing writing and production vision of a series, where the production model uses that role.", why:"Creator, head writer, executive producer, and showrunner are not universally interchangeable titles.", changes:"Team, authority, experience, and series-production claims.", category:"Story & screen" }),
  s({ id:"slate", label:"Slate", aliases:["project slate"], plain:"A curated group of projects developed, financed, represented, or produced together.", why:"A slate is not automatically evidence that every project is equally active or supported.", changes:"Company story, status language, and portfolio presentation.", category:"Story & screen" }),
  s({ id:"chain-of-title", label:"Chain of title", aliases:["rights chain"], plain:"The documented sequence showing how relevant rights in a work moved to the person or entity claiming control.", why:"A creative tool cannot establish ownership from confidence or a logo.", changes:"Rights status, diligence, circulation, and specialist review.", category:"Rights, labour & process" }),
  s({ id:"option", label:"Option", aliases:["option agreement","optioned"], plain:"A time-limited contractual right to acquire or develop specified rights under agreed conditions.", why:"An option, shopping arrangement, interest, and full acquisition are different states.", changes:"Status language, rights claims, dates, and specialist checks.", category:"Rights, labour & process" }),
  s({ id:"shopping-agreement", label:"Shopping agreement", aliases:["shopping arrangement"], plain:"An agreement allowing someone to seek partners or buyers for a project without necessarily acquiring the underlying rights.", why:"Its scope, exclusivity, term, and authority differ from an option.", changes:"Access, status, rights language, and expiration checks.", category:"Rights, labour & process" }),
  s({ id:"release", label:"Release", aliases:["consent release","appearance release"], plain:"A written permission governing a person’s contribution, likeness, material, or participation for stated uses.", why:"Consent should be specific enough to mean something and current enough to rely on.", changes:"Use, privacy, edit rights, circulation, and specialist review.", category:"Rights, labour & process" }),
  s({ id:"advertising-strategy", label:"Advertising strategy", aliases:["comms strategy","brand strategy"], plain:"The reasoned choice of audience, problem, objective, insight, proposition, proof, and role for communication.", why:"Strategy narrows the creative problem; it does not pre-write the execution.", changes:"Concept criteria, channel, messaging, and measurement.", category:"Advertising" }),
  s({ id:"single-minded-proposition", label:"Single-minded proposition", aliases:["SMP","single-minded message"], plain:"The one central promise or thought the communication should make graspable.", why:"Single-minded does not require simple-minded; it creates a centre of gravity.", changes:"Concept, headline, script, and evaluation.", category:"Advertising" }),
  s({ id:"reason-to-believe", label:"Reason to believe", aliases:["RTB","supporting proof"], plain:"The evidence, mechanism, demonstration, experience, or credible source that supports a proposition.", why:"A claim without a reason to believe asks design to perform trust.", changes:"Proof, demonstration, source, and legal review.", category:"Advertising" }),
  s({ id:"mandatories", label:"Mandatories", aliases:["required elements","must-haves"], plain:"Elements a current brief or process requires: claims, logos, product, end frame, language, length, format, or disclosures.", why:"Mandatories are constraints to solve with—not an excuse to hide them at the end.", changes:"Concept feasibility, layout, production, and compliance.", category:"Advertising" }),
  s({ id:"deliverables", label:"Deliverables", aliases:["outputs","assets"], plain:"The specific items, formats, durations, versions, ratios, languages, and files the work must produce.", why:"A campaign idea and its production burden cannot be scoped separately forever.", changes:"Scope, timeline, budget, concept, and handover.", category:"Advertising" }),
  s({ id:"bid", label:"Bid", aliases:["production bid","cost bid"], plain:"A priced proposal for producing defined work under stated assumptions, exclusions, and terms.", why:"A bid is only comparable when scope and assumptions are comparable.", changes:"Production route, procurement, schedule, and risk.", category:"Advertising" }),
  s({ id:"triple-bid", label:"Triple bid", aliases:["three-way bid","competitive bid"], plain:"A procurement process in which several suppliers or directors price or pitch against the same brief.", why:"Competition, fees, use of ideas, time, and decision criteria should be materially clear.", changes:"Labour boundary, process questions, schedule, and scope.", category:"Advertising" }),
  s({ id:"storyboard", label:"Storyboard", aliases:["boards","shooting boards"], plain:"A sequence of drawn frames used to plan shots, action, composition, and continuity.", why:"A storyboard tests visual sequence; it is not the finished film or necessarily the director’s treatment.", changes:"Production planning, timing, and scene clarity.", category:"Advertising" }),
  s({ id:"animatic", label:"Animatic", aliases:["boardomatic"], plain:"A timed edit of storyboard frames, temporary sound, and motion used to test sequence and duration.", why:"It can expose timing and comprehension problems before expensive production.", changes:"Edit, script length, shot plan, and approvals.", category:"Advertising" }),
  s({ id:"previs", label:"Previsualisation", aliases:["previs","previz"], plain:"A rough moving visualisation used to plan complex action, camera, design, or production before the final shoot.", why:"Previs is a planning instrument, not a promise that every temporary choice is final.", changes:"Production method, feasibility, and shot planning.", category:"Advertising" }),
  s({ id:"ppm", label:"Pre-production meeting", aliases:["PPM"], plain:"A formal meeting where key creative, production, client, agency, legal, and logistical details are approved before production.", why:"Late ambiguity becomes expensive on set.", changes:"Approvals, boards, casting, styling, schedule, and responsibility.", category:"Advertising" }),
  s({ id:"usage", label:"Usage", aliases:["media usage","talent usage"], plain:"The agreed ways, places, duration, media, territories, and audiences in which work or a person’s contribution may be used.", why:"Making the asset and licensing its use are separate material questions.", changes:"Rights, budget, deliverables, territories, and renewal.", category:"Rights, labour & process" }),
  s({ id:"buyout", label:"Buyout", aliases:["full buyout"], plain:"A payment or agreement intended to cover specified rights or future uses rather than recurring use fees; scope varies materially.", why:"‘Buyout’ is not one universal bundle and should not be treated as unlimited by vibes.", changes:"Term, media, territory, duration, reuse, and specialist review.", category:"Rights, labour & process" }),
  s({ id:"territory", label:"Territory", aliases:["usage territory","market"], plain:"The geographic area in which specified use, distribution, sales, or rights apply.", why:"Global, regional, national, and platform-specific use carry different scope and cost.", changes:"Usage, licensing, language, budget, and releases.", category:"Rights, labour & process" }),
  s({ id:"exclusivity", label:"Exclusivity", aliases:["exclusive term","category conflict"], plain:"A restriction preventing specified competing work, use, representation, or deals for a defined scope and time.", why:"Broad exclusivity can have a real material cost beyond the immediate fee.", changes:"Terms, conflicts, compensation, and future work.", category:"Rights, labour & process" }),
  s({ id:"pitch-fee", label:"Pitch fee", aliases:["treatment fee","development fee"], plain:"Payment for participating in a pitch or producing requested speculative development work.", why:"A fee does not answer every rights or use question, but it recognises labour has a material cost.", changes:"Participation, scope, terms, and process clarity.", category:"Rights, labour & process" }),
  s({ id:"case-film", label:"Case film", aliases:["award case study","case video"], plain:"A short film explaining a campaign’s problem, idea, execution, and results for awards, sales, or internal learning.", why:"It should distinguish real results from narrative inflation and retrospective theatre.", changes:"Evidence, sourcing, edit, and claims.", category:"Advertising" }),
  s({ id:"tam-sam-som", label:"TAM / SAM / SOM", aliases:["market sizing","total addressable market"], plain:"Three market-size frames: total possible market, realistically serviceable market, and the share plausibly obtainable under stated conditions.", why:"A huge top-down number does not prove a reachable business.", changes:"Market claim, assumptions, source, and go-to-market evidence.", category:"Business & startups" }),
  s({ id:"business-model", label:"Business model", aliases:["revenue model"], plain:"How an organisation creates value, delivers it, and sustains the work financially.", why:"Price is one component; costs, incentives, channels, and who pays also matter.", changes:"Product story, economics, route, and risk.", category:"Business & startups" }),
  s({ id:"unit-economics", label:"Unit economics", aliases:["per-unit economics"], plain:"The revenue and direct cost relationship for one meaningful unit such as a customer, transaction, order, or seat.", why:"Growth can hide a structurally losing unit.", changes:"Pricing, scale claims, funding story, and diligence.", category:"Business & startups" }),
  s({ id:"go-to-market", label:"Go-to-market", aliases:["GTM","route to market"], plain:"The practical system for reaching, acquiring, selling to, onboarding, and retaining a defined customer group.", why:"‘Social media’ is not a complete route to market.", changes:"Audience, channels, sales motion, milestones, and evidence.", category:"Business & startups" }),
  s({ id:"product-market-fit", label:"Product–market fit", aliases:["PMF","market fit"], plain:"A condition in which a defined market repeatedly gets meaningful value from a product strongly enough to sustain use, demand, or payment.", why:"It is an evidence question, not a badge awarded by a deck.", changes:"Claims, growth strategy, metrics, and funding story.", category:"Business & startups" }),
  s({ id:"ideal-customer-profile", label:"Ideal customer profile", aliases:["ICP","ideal customer"], plain:"The type of organisation or customer for whom the offer is most relevant, viable, and valuable under current evidence.", why:"A target list is not an ICP; the profile explains fit conditions.", changes:"Positioning, sales route, proof, and product priorities.", category:"Business & startups" }),
  s({ id:"persona", label:"Persona", aliases:["buyer persona","user persona"], plain:"A research-based model of a user or buyer pattern used to make needs, contexts, and behaviours discussable.", why:"A persona is a tool, not a fictional stereotype dressed as research.", changes:"Journey, language, feature decisions, and testing.", category:"Business & startups" }),
  s({ id:"traction", label:"Traction", aliases:["market traction","momentum"], plain:"Current evidence of meaningful adoption, demand, revenue, retention, partnership, or use—defined precisely.", why:"A press mention, waitlist, pilot, signed contract, and recurring revenue are not the same proof.", changes:"Funding story, risk, milestones, and claim strength.", category:"Evidence & claims" }),
  s({ id:"vanity-metric", label:"Vanity metric", aliases:["vanity numbers"], plain:"A number that looks impressive but does not reliably explain value, behaviour, health, or the decision at hand.", why:"Magnitude can distract from relevance.", changes:"Metric selection, narrative, and questions the data can honestly answer.", category:"Evidence & claims" }),
  s({ id:"retention", label:"Retention", aliases:["customer retention","user retention"], plain:"The proportion or pattern of people who continue using, buying, or engaging after a defined period.", why:"Acquisition without retention can mistake a leaky bucket for growth.", changes:"Product–market fit claim, cohorts, economics, and roadmap.", category:"Business & startups" }),
  s({ id:"churn", label:"Churn", aliases:["attrition","customer churn"], plain:"The rate or count at which customers, users, revenue, or subscriptions leave during a defined period.", why:"Customer churn and revenue churn can tell different stories.", changes:"Retention work, forecasts, unit economics, and risk.", category:"Business & startups" }),
  s({ id:"cohort", label:"Cohort", aliases:["cohort analysis"], plain:"A group sharing a start time or relevant characteristic, tracked together to compare behaviour over time.", why:"Aggregates can hide whether newer groups behave better or worse.", changes:"Retention evidence, product learning, and forecasts.", category:"Evidence & claims" }),
  s({ id:"pipeline", label:"Pipeline", aliases:["sales pipeline","deal pipeline"], plain:"Potential opportunities moving through defined stages toward a decision or close.", why:"Pipeline value is not revenue; stage, probability, age, and concentration matter.", changes:"Forecast, sales story, milestones, and risk.", category:"Business & startups" }),
  s({ id:"roadmap", label:"Roadmap", aliases:["product roadmap","delivery roadmap"], plain:"A time-oriented statement of intended outcomes, priorities, dependencies, and learning—not a guaranteed feature calendar.", why:"False precision makes uncertainty look managed while hiding real dependencies.", changes:"Milestones, sequencing, resourcing, and promises.", category:"Business & startups" }),
  s({ id:"milestone", label:"Milestone", aliases:["key milestone"], plain:"A verifiable point showing that a meaningful piece of work, evidence, approval, or capability now exists.", why:"Activity is not automatically progress.", changes:"Plan, use of funds, timeline, and next decision.", category:"Business & startups" }),
  s({ id:"use-of-funds", label:"Use of funds", aliases:["funding allocation"], plain:"How requested capital is intended to create specific capabilities, milestones, evidence, or runway.", why:"A category pie chart does not by itself explain why this amount changes the business.", changes:"Funding ask, milestones, budget basis, and diligence.", category:"Business & startups" }),
  s({ id:"runway", label:"Runway", aliases:["cash runway"], plain:"The estimated time available before cash is exhausted under explicit current burn and cash assumptions.", why:"Runway is sensitive to changing costs, revenue, timing, and restricted funds.", changes:"Funding timing, risk, hiring, and scenario planning.", category:"Business & startups" }),
  s({ id:"cap-table", label:"Capitalisation table", aliases:["cap table","ownership table"], plain:"A record of equity ownership, options, convertibles, and related claims in a company.", why:"It is diligence material, not decorative proof, and must be current and handled carefully.", changes:"Ownership, financing, dilution, and specialist review.", category:"Rights, labour & process" }),
  s({ id:"valuation", label:"Valuation", aliases:["company valuation","pre-money valuation"], plain:"An agreed or proposed value used in a financing or transaction context, based on specific terms and timing.", why:"A valuation is not an objective score of human worth or permanent business value.", changes:"Financing terms, dilution, negotiation, and specialist work.", category:"Business & startups" }),
  s({ id:"term-sheet", label:"Term sheet", aliases:["heads of terms"], plain:"A document outlining principal proposed deal terms before definitive agreements.", why:"Its legal effect and binding provisions vary; a pitch tool should not interpret it as advice.", changes:"Negotiation, diligence, ownership, control, and specialist review.", category:"Rights, labour & process" }),
  s({ id:"due-diligence", label:"Due diligence", aliases:["diligence"], plain:"A structured investigation of claims, rights, finances, risks, operations, people, or evidence before a consequential decision.", why:"A confident deck is not a substitute for inspectable facts.", changes:"Data room, sources, disclosures, and specialist checks.", category:"Evidence & claims" }),
  s({ id:"claim", label:"Claim", aliases:["assertion","statement of fact"], plain:"A statement presented as true, likely, or supportable about the work, market, result, person, right, or future.", why:"Different claims need different evidence and some should not be made yet.", changes:"Source, wording, footing, disclosure, and specialist review.", category:"Evidence & claims" }),
  s({ id:"assumption", label:"Assumption", aliases:["working assumption","hypothesis"], plain:"A belief temporarily treated as usable so work can proceed, while its uncertainty remains visible.", why:"An assumption becomes dangerous when design quietly turns it into a fact.", changes:"Testing, labels, scenario, and result footing.", category:"Evidence & claims" }),
  s({ id:"evidence", label:"Evidence", aliases:["proof","support"], plain:"Information or observation relevant to whether a specific claim is supportable.", why:"Evidence has scope, source, freshness, quality, and limits; it is not a decorative noun.", changes:"Claim strength, route, caveat, and decision confidence.", category:"Evidence & claims" }),
  s({ id:"proof-point", label:"Proof point", aliases:["support point","evidence point"], plain:"A concise piece of relevant evidence used to support one declared claim.", why:"One proof point should not be forced to prove everything.", changes:"Page job, hierarchy, source, and narrative order.", category:"Evidence & claims" }),
  s({ id:"primary-source", label:"Primary source", aliases:["first-hand source","original source"], plain:"The original record, data, document, person, or direct observation closest to the claim being checked.", why:"Retellings may lose scope, date, conditions, or contradiction.", changes:"Citation, verification, and result footing.", category:"Evidence & claims" }),
  s({ id:"citation", label:"Citation", aliases:["source line","reference"], plain:"A visible pointer that lets someone identify and inspect the source supporting a claim.", why:"‘Source: internet’ is not inspectable evidence.", changes:"Layout, appendix, claim credibility, and compliance.", category:"Evidence & claims" }),
  s({ id:"sample-size", label:"Sample size", aliases:["n value","number of respondents"], plain:"The number of observations or participants behind a result, interpreted with method and selection—not alone.", why:"A large biased sample and a small useful qualitative sample answer different questions.", changes:"Claim scope, caveat, and research interpretation.", category:"Evidence & claims" }),
  s({ id:"correlation-causation", label:"Correlation and causation", aliases:["correlation is not causation"], plain:"Correlation means two things vary together; causation claims one materially produces change in the other.", why:"A chart can show association without proving the reason.", changes:"Claim wording, evidence need, and causal language.", category:"Evidence & claims" }),
  s({ id:"projection", label:"Projection", aliases:["forecast","future estimate"], plain:"A forward estimate built from explicit assumptions, current evidence, and a defined model.", why:"A smooth upward line is not evidence; the assumptions are the argument.", changes:"Scenario, source, range, and specialist review.", category:"Evidence & claims" }),
  s({ id:"data-room", label:"Data room", aliases:["diligence room","virtual data room"], plain:"A controlled collection of current documents and evidence shared for qualified diligence.", why:"Access, versioning, privacy, and source integrity matter more than volume.", changes:"Permissions, indexing, disclosures, and diligence workflow.", category:"Evidence & claims" }),
  s({ id:"information-hierarchy", label:"Information hierarchy", aliases:["visual hierarchy","hierarchy"], plain:"The ordering and visual emphasis that tells people what to notice first, next, and last.", why:"Everything cannot be the headline without turning the page into static.", changes:"Type, scale, spacing, sequence, and editing.", category:"Rooms & slides" }),
  s({ id:"whitespace", label:"White space", aliases:["negative space","breathing room"], plain:"Unoccupied visual space used to create hierarchy, rhythm, grouping, calm, or emphasis.", why:"Space is not wasted merely because no content was crammed into it.", changes:"Layout, density, pacing, and attention.", category:"Rooms & slides" }),
  s({ id:"contrast", label:"Contrast", aliases:["visual contrast","tonal contrast"], plain:"A meaningful difference in size, colour, value, weight, shape, position, or motion that helps people distinguish and prioritise information.", why:"Subtlety without legibility is just concealment.", changes:"Hierarchy, accessibility, focus, and rhythm.", category:"Rooms & slides" }),
  s({ id:"reading-order", label:"Reading order", aliases:["content order","focus order"], plain:"The sequence in which people and assistive technologies encounter the information.", why:"Visual placement and document structure can tell different stories.", changes:"Layout, DOM order, keyboard use, export, and accessibility.", category:"Access & inclusion" }),
  s({ id:"speaker-notes", label:"Speaker notes", aliases:["presenter notes","talk track notes"], plain:"Private prompts supporting a live presenter without becoming visible copy the audience must also read.", why:"Useful notes keep the slide from turning into a teleprompter.", changes:"Live density, rehearsal, and handover.", category:"Rooms & slides" }),
  s({ id:"data-visualisation", label:"Data visualisation", aliases:["data viz","chart"], plain:"A visual encoding of data designed to make a specific comparison, pattern, distribution, or change inspectable.", why:"Decoration can make numbers memorable while making their meaning less honest.", changes:"Chart choice, annotation, source, scale, and page job.", category:"Rooms & slides" }),
  s({ id:"visual-metaphor", label:"Visual metaphor", aliases:["metaphoric image"], plain:"A visual relationship that uses one familiar thing to illuminate another idea.", why:"A metaphor should clarify or deepen the point, not merely make a stock photo feel clever.", changes:"Concept, image choice, copy, and cultural review.", category:"Rooms & slides" }),
  s({ id:"sequence", label:"Sequence", aliases:["slide sequence","order"], plain:"The deliberate order in which pages create understanding, tension, proof, and decision readiness.", why:"Good pages in the wrong order can make the audience do the editor’s work.", changes:"Narrative, transitions, repetition, and reveal.", category:"Rooms & slides" }),
  s({ id:"transition", label:"Transition", aliases:["bridge","segue"], plain:"The logical or emotional bridge that makes the move from one page or idea to the next feel earned.", why:"Motion effects cannot repair a missing argumentative bridge.", changes:"Sequence, spoken delivery, and page openings.", category:"Rooms & slides" }),
  s({ id:"progressive-disclosure", label:"Progressive disclosure", aliases:["reveal detail gradually"], plain:"Showing the essential choice or information first, with deeper detail available when the person needs or chooses it.", why:"It hides complexity, not consequences.", changes:"Navigation, expert mode, accordions, and user control.", category:"Rooms & slides" }),
  s({ id:"cognitive-load", label:"Cognitive load", aliases:["mental load","processing load"], plain:"The amount of attention and working memory an experience asks someone to use at once.", why:"Confusion can come from simultaneous demands even when every sentence is individually clear.", changes:"Sequence, density, labels, choices, and channel competition.", category:"Access & inclusion" }),
  s({ id:"plain-language", label:"Plain language", aliases:["plain English","clear language"], plain:"Writing people can understand and use the first time, without removing necessary meaning or talking down to them.", why:"Clarity is an access practice, not an absence of intelligence.", changes:"Vocabulary, sentence structure, labels, and definitions.", category:"Access & inclusion" }),
  s({ id:"alt-text", label:"Alt text", aliases:["alternative text","image description"], plain:"A concise text alternative communicating the relevant purpose or information of an image to people who cannot access it visually.", why:"It should serve the image’s job in context—not inventory every pixel.", changes:"Image markup, editorial judgement, and accessibility.", category:"Access & inclusion" }),
  s({ id:"captions", label:"Captions", aliases:["closed captions","subtitles for speech"], plain:"Synchronized text representing speech and relevant audio information in moving media.", why:"Captions support Deaf and hard-of-hearing people and many others in real viewing conditions.", changes:"Video deliverables, timing, speaker labels, and sound cues.", category:"Access & inclusion" }),
  s({ id:"colour-contrast", label:"Colour contrast", aliases:["contrast ratio","text contrast"], plain:"The perceptual difference between foreground and background needed for content and controls to remain distinguishable.", why:"Brand subtlety does not outrank legibility.", changes:"Colour tokens, type, states, and accessibility testing.", category:"Access & inclusion" }),
  s({ id:"localisation", label:"Localisation", aliases:["l10n","market adaptation"], plain:"Adapting language, content, format, examples, legal needs, and cultural context for a particular locale.", why:"Translation alone may preserve words while breaking meaning or use.", changes:"Copy, layout, imagery, date and number formats, and review.", category:"Access & inclusion" }),
  s({ id:"translation", label:"Translation", aliases:["translated copy"], plain:"Rendering meaning from one language into another for a defined audience and use.", why:"Word counts, reading speed, line breaks, register, and cultural implications can materially change.", changes:"Copy fit, review, typography, and source language.", category:"Access & inclusion" }),
  s({ id:"accessibility", label:"Accessibility", aliases:["a11y","inclusive access"], plain:"Designing so people with varied bodies, senses, cognition, language, technology, and environments can perceive, understand, navigate, and act.", why:"Accessibility is part of the product’s function, not a compliance garnish.", changes:"Content, interaction, code, media, testing, and procurement.", category:"Access & inclusion" }),
  s({ id:"nda", label:"Non-disclosure agreement", aliases:["NDA","confidentiality agreement"], plain:"An agreement governing defined confidential information and permitted disclosure or use.", why:"An NDA does not automatically establish rights, payment, safety, or the fairness of every term.", changes:"Disclosure, access, storage, circulation, and specialist review.", category:"Rights, labour & process" }),
  s({ id:"embargo", label:"Embargo", aliases:["publication embargo"], plain:"A time or condition before which specified information must not be published or disclosed.", why:"Embargoes need a clear scope, owner, and end condition.", changes:"Timing, recipients, access, and public assets.", category:"Rights, labour & process" }),
  s({ id:"confidentiality", label:"Confidentiality", aliases:["confidential material","private information"], plain:"A duty or agreed boundary limiting how specified information is disclosed, stored, or used.", why:"A deck can accidentally reveal more than the decision requires.", changes:"Redaction, circulation, versioning, and access.", category:"Rights, labour & process" }),
  s({ id:"work-for-hire", label:"Work made for hire", aliases:["work for hire","commissioned ownership"], plain:"A legal ownership concept whose meaning depends on jurisdiction, relationship, category, and agreement.", why:"Payment alone does not let a creative tool declare who owns what.", changes:"Contract, credit, rights, reuse, and qualified legal review.", category:"Rights, labour & process" }),
  s({ id:"licence", label:"Licence", aliases:["license","licensed use"], plain:"Permission to use specified rights under defined conditions without necessarily transferring ownership.", why:"Scope, media, duration, territory, exclusivity, and sublicensing matter.", changes:"Use, attribution, price, renewal, and specialist review.", category:"Rights, labour & process" }),
  s({ id:"moral-rights", label:"Moral rights", aliases:["right of attribution","integrity right"], plain:"Creator rights relating to attribution and integrity that vary by jurisdiction and may not behave like ordinary economic rights.", why:"Ownership, licence, credit, and moral rights are not one interchangeable bundle.", changes:"Credit, adaptation, waiver language, and specialist review.", category:"Rights, labour & process" }),
  s({ id:"credit", label:"Credit", aliases:["creator credit","billing"], plain:"How a person’s contribution and role are named in the work, publicity, records, or contract.", why:"Credit is material recognition and can shape future work; it should not be inferred from participation.", changes:"Terms, hierarchy, publicity, and version copy.", category:"Rights, labour & process" }),
  s({ id:"kill-fee", label:"Kill fee", aliases:["cancellation fee","termination fee"], plain:"Payment due when commissioned or reserved work is cancelled under stated conditions.", why:"Cancellation can still consume time, opportunity, and labour.", changes:"Terms, schedule, participation, and risk.", category:"Rights, labour & process" }),
  s({ id:"scope-creep", label:"Scope creep", aliases:["expanding scope","moving goalposts"], plain:"Work expanding beyond the agreed deliverables, rounds, use, timing, or responsibility without an explicit new decision.", why:"Small additions accumulate into unpriced labour and muddled accountability.", changes:"Change request, fee, schedule, and boundaries.", category:"Rights, labour & process" }),
  s({ id:"revision-round", label:"Revision round", aliases:["round of changes","feedback round"], plain:"One agreed cycle of consolidated feedback and response against a defined stage or deliverable.", why:"A round is not every stakeholder sending contradictory notes on different days.", changes:"Scope, approvals, timeline, and version control.", category:"Rights, labour & process" }),
  s({ id:"approval", label:"Approval", aliases:["sign-off","final approval"], plain:"A recorded decision that a defined person accepts a defined version for a defined next use or stage.", why:"Silence, enthusiasm, attendance, and approval are not the same state.", changes:"Version, production, spend, release, and accountability.", category:"Rights, labour & process" }),
  s({ id:"version-control", label:"Version control", aliases:["versioning","file version"], plain:"A reliable way to know which state of the work is current, who changed it, and what it may be used for.", why:"‘Final-final-REAL’ is not a governance system.", changes:"File naming, approvals, handover, and rollback.", category:"Rights, labour & process" }),
  s({ id:"handover", label:"Handover", aliases:["handoff","delivery handover"], plain:"The transfer of current files, context, decisions, permissions, dependencies, and responsibility to the next person or team.", why:"A folder dump moves files; a handover preserves the ability to act responsibly.", changes:"Documentation, file map, provenance, and ownership.", category:"Rights, labour & process" }),
  s({ id:"conflict-of-interest", label:"Conflict of interest", aliases:["conflict"], plain:"A situation in which a person’s competing duties, relationships, or interests may impair—or appear to impair—independent judgement.", why:"Disclosure and process can matter even when nobody intended harm.", changes:"Participation, disclosure, recusal, and specialist guidance.", category:"Rights, labour & process" }),
  s({ id:"procurement", label:"Procurement", aliases:["vendor procurement","sourcing process"], plain:"The organisational process for selecting, approving, contracting, and paying suppliers or services.", why:"Creative enthusiasm does not bypass vendor, legal, risk, or purchasing gates.", changes:"Route, timeline, documentation, and decision owners.", category:"Rights, labour & process" }),
  s({ id:"consent", label:"Consent", aliases:["informed consent","permission"], plain:"A specific, informed, freely given, and revocable agreement to a defined participation or use where revocation is possible.", why:"Silence, pressure, dependence, or a vague blanket checkbox may not create meaningful consent.", changes:"Participation, recording, disclosure, use, and privacy.", category:"Rights, labour & process" }),
] as const;

const storyIds = new Set(["logline","tagline","synopsis","series-engine","limited-series","season-arc","episode-examples","episode-list","pilot","pitch-bible","production-bible","lookbook","treatment","directors-treatment","theme","visual-reference"]);
const rightsIds = new Set(["attachment","image-provenance","specialist-first","speculative-work","paid-help","portfolio-work","current-requirement","source-freshness","requirement-state"]);
const slideIds = new Set(["page-job","section-job","reader-question","copy-band","preview-fit","smallest-view","type-pressure","channel-competition","split-source","mechanical-split","delivery-mode","live-deck","leave-behind","dual-use","appendix","reference-slide"]);
const evidenceIds = new Set(["market-proof","result-footing","confidence","score","convention"]);
function categoryFor(term: DictionaryTerm): Category {
  if (storyIds.has(term.id)) return "Story & screen";
  if (rightsIds.has(term.id)) return "Rights, labour & process";
  if (slideIds.has(term.id)) return "Rooms & slides";
  if (evidenceIds.has(term.id)) return "Evidence & claims";
  return "Foundations";
}

export const TERMS: readonly PitchTerm[] = [
  ...DICTIONARY_TERMS.map((term) => ({ ...term, category: categoryFor(term) })),
  ...EXTRA,
].map(forDisplay).sort((a, b) => a.label.localeCompare(b.label));

export const CATEGORIES: readonly Category[] = ["Foundations","Story & screen","Advertising","Business & startups","Rooms & slides","Evidence & claims","Rights, labour & process","Access & inclusion"];
